### ISSUE TITLE
I cannot get this to work from the vue app and my components

### ISSUE THREAD

**Issue by rlneub** [officert/vue-slideout-panel#40]
I am 1 week into vue. I have a application that has 6 components which is working nicely, but the snippits on the website show everything from a plain JS and not using the vue app.

Can you please provide me an installation for

main.js
app.vue
parentcomponent.vue
your panel1.vue

I have spent over 5 hours without success

I get this.$emit not defined
<slideout-panel> not defined
and various other errors 

This component really looks good on appearance but the documentation is one sided in explaining how to run. I need examples from the vue hello world app.

I did get your examples to run but not in the vue app framework.

Thanks for your help

my email is rick@drneubrander.com

**Comment by officert** [comment]
It's hard to give specific instructions without seeing more about how your app is setup. You mentiond the "vue app framework", though I'm not sure what you mean because all the examples are in Vue. Can you paste in examples of your components?

Basically in your `main.js` you need to install the Slide-out panel component and register whatever component you want to have in the slide out panel:

```js
import VueSlideoutPanel from 'vue2-slideout-panel';

Vue.use(VueSlideoutPanel);

import Panel1 from 'components/Panel1';

Vue.component('panel1', Panel1);
```

Then in your parent component you need a method that calls `this.$showPanel`:

```js
methods: {
  showPanel1() {
    this.$showPanel({
       component: "panel-1",
       props: {}
    });
  }
}
```
